### ISSUE TITLE
ACRE 2?

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/OP_Hand_of_God#2]
Thoughts on using this mission to test ACRE 2 performance?  At least during the testing phase.  If it doesn't work out we can switch back to TFAR for release.

**Comment by coachwn** [comment]
We can try it...god I hate ACRE....

**Comment by jerkinmerkin** [comment]
I haven't been the biggest fan of it either, but it's been a few updates since we tried it so I say we give it a chance.  Plus, it's got ITF radios I'd like to use.
