### ISSUE TITLE
Basic medical items

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/OP_Hand_of_God#3]
So there's been quite a few ACE updates since I first took a look at basic soldier medical kit.  I'm still using the set up from back in Noble Reaolve which is 4x packing, 4x elastic, and 2x tourniquets.  Is there anything that needs changing?  Are field bandages worth a damn yet?

**Comment by jerkinmerkin** [comment]
I should note that this mission takes place in 1982, so I don't believe quick-clot was around then, correct?

**Comment by coachwn** [comment]
No it wasn't. Packing should be around 10x....take a look at the [Tanoa](https://github.com/Spearhead-Gaming-Milsim/Tanoa-Takedown) sqf's that @FoxKilo posted in the main part there. It should have exactly what the loadouts are and then adjust based on what that time frame is. 

So honestly things like M4's didn't exist but you could give them M16A1/M203, M16A1 and M-60; maybe one or two sets of NVG's at the most...That is about the limit of what a high speed unit would have carried back then. Not that much variation from the regular soldiers just more

**Comment by FoxKilo** [comment]
So just to clarify the medical in our team kits is different to what gets taught in CLS, main difference is that everyone else has logistic/medical support and we don't. For a basic medical loadout I would say;

4 x TQs 5x Packing 5x elastic.

field bandages etc are all implemented and can be used, it's just that the combination of elastic/packing will deal with around 80% of all injuries.

**Comment by jerkinmerkin** [comment]
Yea this issue is seperate then SOF basic medical loadouts.  I have your base setup.  This is for the Cav and Inf grunts.

**Comment by coachwn** [comment]
If you are going with a 1980's (specifically early 80's) then the medical stuff was drastically different to the point of it was nowhere near as specific as it is today. In fact I still have a complete US Army combat medic with the stuff in it from 1989. Guess what; the loadout is exactly as follows: gloves, gauze packing (no badages), regular bandages, gauze wrap, elastic wraps, tourniquets, scissors, tweezers, forceps and chest sealers. No fluids of any type. That stuff was issued on an as needed basis from what I remember as well. The only times fluid was pushed was plasma or saline and even then it was only pushed IF they had it available. Most all of the medics were taught to monitor vitals and prepare the patient for immediate evac if possible.

**Comment by FoxKilo** [comment]
Aye I know, Nichols was referencing the SOF loadouts so didn't want things to get confusing.

Quickclot was invented in 1984 and then developed as a bandage long after. So a mixture of field dressing, packing and elastic would be suitable.

**Comment by jerkinmerkin** [comment]
Fox, if you want to get with Lim and adjust SOF medical loutouts to fit the timeframe and scenario I'd be happy to implement it.

**Comment by coachwn** [comment]
Hey for medical that was a broad brush since it was not drastically different across the board. I think you guys are going to be super limited in what TCCC was back then; especially in a scenario related to a middle eastern country. Everyone is getting sticks for crutches with torn apart shirts to act as bandages and mud poltice compresses....:D

**Comment by jerkinmerkin** [comment]
Allah (PBUH) will heal the wounds.

**Comment by CoverOpe** [comment]
Sorry, been at work.  The basic bandages pretty much only work for basic ACE medical. They will almost always pop off on any wounds.  You can scrap quik clot if not period, but I would add a few more packing to replace them.  While it might be period to not have fluids, it won't be fun and will take a lot away from an already pretty limited role.  I think the only thing that should be futzed with is the quik clot.  Load outs are of course up to each unit, but I almost always carry more than what's given.  The current deployment actually had a pretty solid load out from what I've noticed so maybe take ideas from that.  Tl;dr playing medic will suck without at least: packing bandages, elastic bandages, Tourniquets, fluids and medications.  I don't think bleed rate changes based on fluids are a thing yet (citation needed) so fluids type doesn't matter.  Just have to balance fun and immersion on this one IMO

**Comment by CoverOpe** [comment]
For everyone's quick reference, packing: velocity, avulsions.  Elastic: everything else.  Combining them will not increase the chance of things staying on etc.  Quik clot is pretty much only used for Large Velocity wounds.  So losing them is not a big deal. Hope that helps :)

**Comment by CoverOpe** [comment]
In regards to a soldiers basic kit, I think Fox's suggestion is perfectly fine.  Normal soldiers definitely shouldn't be handling fluids unless heavy casualties are expected on a mission and they only need a few bandages.  (Sorry for multiple posts, was on phone then re-read thread on PC).  I have some time tonight so I'm going to go ahead and update my medical testing graph thing and see if there's anything different.  I'll update later.
